In [1]:
import pandas as pd
import numpy as np

In [2]:
vis_data = pd.read_csv("train.csv", encoding = 'ISO-8859-1', low_memory = False)

In [3]:
vis_data

ticket_id                                     agency_name  \
0           22056  Buildings, Safety Engineering & Env Department   
1           27586  Buildings, Safety Engineering & Env Department   
2           22062  Buildings, Safety Engineering & Env Department   
3           22084  Buildings, Safety Engineering & Env Department   
4           22093  Buildings, Safety Engineering & Env Department   
...           ...                                             ...   
250301     325555  Buildings, Safety Engineering & Env Department   
250302     325557  Buildings, Safety Engineering & Env Department   
250303     325562  Buildings, Safety Engineering & Env Department   
250304     325559  Buildings, Safety Engineering & Env Department   
250305     325561  Buildings, Safety Engineering & Env Department   

          inspector_name                      violator_name  \
0        Sims, Martinzie  INVESTMENT INC., MIDWEST MORTGAGE   
1       Williams, Darrin           Michigan, Covenant House   
2        Sims, Martinzie                    SANDERS, DERRON   
3        Sims, Martinzie                       MOROSI, MIKE   
4        Sims, Martinzie                    NATHANIEL, NEAL   
...                  ...                                ...   
250301      Bush, Wesley    WESTGATE TERRACE APARTMENTS LLC   
250302      Bush, Wesley    WESTGATE TERRACE APARTMENTS LLC   
250303      Bush, Wesley    WESTGATE TERRACE APARTMENTS LLC   
250304      Bush, Wesley    WESTGATE TERRACE APARTMENTS LLC   
250305      Bush, Wesley    WESTGATE TERRACE APARTMENTS LLC   

        violation_street_number violation_street_name  violation_zip_code  \
0                        2900.0                 TYLER                 NaN   
1                        4311.0               CENTRAL                 NaN   
2                        1449.0            LONGFELLOW                 NaN   
3                        1441.0            LONGFELLOW                 NaN   
4                        2449.0             CHURCHILL                 NaN   
...                         ...                   ...                 ...   
250301                  10701.0           SANTA MARIA                 NaN   
250302                  10701.0             MEYERS RD                 NaN   
250303                  10701.0             MEYERS RD                 NaN   
250304                  10701.0             MEYERS RD                 NaN   
250305                  10701.0             MEYERS RD                 NaN   

        mailing_address_str_number mailing_address_str_name     city  ...  \
0                              3.0                S. WICKER  CHICAGO  ...   
1                           2959.0       Martin Luther King  Detroit  ...   
2                          23658.0                 P.O. BOX  DETROIT  ...   
3                              5.0                ST. CLAIR  DETROIT  ...   
4                           7449.0                CHURCHILL  DETROIT  ...   
...                            ...                      ...      ...  ...   
250301                      1715.0                   MEYERS  DETROIT  ...   
250302                      1715.0                   MEYERS  DETROIT  ...   
250303                      1715.0                   MEYERS  DETROIT  ...   
250304                      1715.0                   MEYERS  DETROIT  ...   
250305                      1715.0                   MEYERS  DETROIT  ...   

       clean_up_cost judgment_amount payment_amount balance_due  \
0                0.0           305.0            0.0       305.0   
1                0.0           855.0          780.0        75.0   
2                0.0             0.0            0.0         0.0   
3                0.0             0.0            0.0         0.0   
4                0.0             0.0            0.0         0.0   
...              ...             ...            ...         ...   
250301           0.0             0.0            0.0         0.0   
250302           0.0             0.0

In [4]:
vis_data.keys()


Index(['ticket_id', 'agency_name', 'inspector_name', 'violator_name',
       'violation_street_number', 'violation_street_name',
       'violation_zip_code', 'mailing_address_str_number',
       'mailing_address_str_name', 'city', 'state', 'zip_code',
       'non_us_str_code', 'country', 'ticket_issued_date', 'hearing_date',
       'violation_code', 'violation_description', 'disposition', 'fine_amount',
       'admin_fee', 'state_fee', 'late_fee', 'discount_amount',
       'clean_up_cost', 'judgment_amount', 'payment_amount', 'balance_due',
       'payment_date', 'payment_status', 'collection_status',
       'grafitti_status', 'compliance_detail', 'compliance'],
      dtype='object')

In [5]:
vis_data['state']

0         IL
1         MI
2         MI
3         MI
4         MI
          ..
250301    MI
250302    MI
250303    MI
250304    MI
250305    MI
Name: state, Length: 250306, dtype: object

In [6]:
vis_data.city.mode()[0]

'DETROIT'

In [7]:
vis_data.state.value_counts().keys()[0]

'MI'

In [8]:
state.mode()[0]

NameError: name 'state' is not defined

In [9]:
vis_data.state.mode()[0]
#test_data['three'].max()

'MI'

In [10]:
result=vis_data['state'].fillna(vis_data.state.mode()[0])

In [11]:
result=vis_data['state'].fillna(vis_data.state.value_counts().keys()[0])

In [12]:
result

0         IL
1         MI
2         MI
3         MI
4         MI
          ..
250301    MI
250302    MI
250303    MI
250304    MI
250305    MI
Name: state, Length: 250306, dtype: object

In [13]:
def most_frequent(List):
    counter = 0
    num = List[0]
    for i in vis_data['state']:
        curr_frequency = List.count(i)
        if(curr_frequency> counter):
            counter = curr_frequency
            num = i
    return num
#List = [2, 1, 2, 2, 1, 3]
#print(most_frequent(vis_data['state']))

In [14]:
test_data = pd.DataFrame([[1, 2, 0], [3, 0, 4], [1, 1, 1], [1, 1, 1],
                          [0, 1, 2]], columns=['one', 'two', 'three'])

In [15]:
test_data

one  two  three
0    1    2      0
1    3    0      4
2    1    1      1
3    1    1      1
4    0    1      2

In [16]:
dfl = test_data.nlargest(1,'three')
dfl

one  two  three
1    3    0      4

In [17]:
test_data[1:3].nlargest

<bound method DataFrame.nlargest of    one  two  three
1    3    0      4
2    1    1      1>

In [18]:
test_data['three'].nlargest

<bound method Series.nlargest of 0    0
1    4
2    1
3    1
4    2
Name: three, dtype: int64>

In [19]:
test_data.nlargest(1, ['three'])



one  two  three
1    3    0      4

In [20]:
test_data = pd.DataFrame([[1, 2, 0], [3, 0, 4], [1, 1, 1], [1, 1, 1],
                          [0, 1, 2]], columns=['one', 'two', 'three'])

In [21]:
test_data.nlargest(1, ['three'])

one  two  three
1    3    0      4

In [22]:
test_data['three'].max()

4

In [23]:
test_data = pd.DataFrame([[1, 2, np.nan], [3, np.nan, 417], [0, 10, -212]], columns=['one', 'two', 'three'])

In [24]:
test_data

one   two  three
0    1   2.0    NaN
1    3   NaN  417.0
2    0  10.0 -212.0

In [25]:
test_data=test_data.fillna(0)

In [26]:
test_data

one   two  three
0    1   2.0    0.0
1    3   0.0  417.0
2    0  10.0 -212.0

In [27]:
from sklearn.preprocessing import MinMaxScaler

In [28]:
vis_data['balance_due']


0         305.0
1          75.0
2           0.0
3           0.0
4           0.0
          ...  
250301      0.0
250302      0.0
250303      0.0
250304      0.0
250305      0.0
Name: balance_due, Length: 250306, dtype: float64

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
x= vis_data['balance_due']

In [31]:
x

0         305.0
1          75.0
2           0.0
3           0.0
4           0.0
          ...  
250301      0.0
250302      0.0
250303      0.0
250304      0.0
250305      0.0
Name: balance_due, Length: 250306, dtype: float64

In [32]:
scaler = StandardScaler()
z=scaler.fit_transform(x.values.reshape(-1,1))

In [33]:
x

0         305.0
1          75.0
2           0.0
3           0.0
4           0.0
          ...  
250301      0.0
250302      0.0
250303      0.0
250304      0.0
250305      0.0
Name: balance_due, Length: 250306, dtype: float64

In [34]:
x.values

array([305.,  75.,   0., ...,   0.,   0.,   0.])

In [35]:
x.values.reshape(-1,1)

array([[305.],
       [ 75.],
       [  0.],
       ...,
       [  0.],
       [  0.],
       [  0.]])

In [36]:
x.values.reshape(-1,1)

array([[305.],
       [ 75.],
       [  0.],
       ...,
       [  0.],
       [  0.],
       [  0.]])

In [37]:
x.values.reshape(-1,1).min()

-7750.0

In [38]:
z.ravel().min()

-13.147334652567258

In [39]:
x.values

array([305.,  75.,   0., ...,   0.,   0.,   0.])

In [40]:
x.values.reshape(-1,1)

array([[305.],
       [ 75.],
       [  0.],
       ...,
       [  0.],
       [  0.],
       [  0.]])

In [41]:
z

array([[ 0.13613444],
       [-0.24315767],
       [-0.36683987],
       ...,
       [-0.36683987],
       [-0.36683987],
       [-0.36683987]])

In [42]:
z.ravel()

array([ 0.13613444, -0.24315767, -0.36683987, ..., -0.36683987,
       -0.36683987, -0.36683987])

In [43]:
vis_data

ticket_id                                     agency_name  \
0           22056  Buildings, Safety Engineering & Env Department   
1           27586  Buildings, Safety Engineering & Env Department   
2           22062  Buildings, Safety Engineering & Env Department   
3           22084  Buildings, Safety Engineering & Env Department   
4           22093  Buildings, Safety Engineering & Env Department   
...           ...                                             ...   
250301     325555  Buildings, Safety Engineering & Env Department   
250302     325557  Buildings, Safety Engineering & Env Department   
250303     325562  Buildings, Safety Engineering & Env Department   
250304     325559  Buildings, Safety Engineering & Env Department   
250305     325561  Buildings, Safety Engineering & Env Department   

          inspector_name                      violator_name  \
0        Sims, Martinzie  INVESTMENT INC., MIDWEST MORTGAGE   
1       Williams, Darrin           Michigan, Covenant House   
2        Sims, Martinzie                    SANDERS, DERRON   
3        Sims, Martinzie                       MOROSI, MIKE   
4        Sims, Martinzie                    NATHANIEL, NEAL   
...                  ...                                ...   
250301      Bush, Wesley    WESTGATE TERRACE APARTMENTS LLC   
250302      Bush, Wesley    WESTGATE TERRACE APARTMENTS LLC   
250303      Bush, Wesley    WESTGATE TERRACE APARTMENTS LLC   
250304      Bush, Wesley    WESTGATE TERRACE APARTMENTS LLC   
250305      Bush, Wesley    WESTGATE TERRACE APARTMENTS LLC   

        violation_street_number violation_street_name  violation_zip_code  \
0                        2900.0                 TYLER                 NaN   
1                        4311.0               CENTRAL                 NaN   
2                        1449.0            LONGFELLOW                 NaN   
3                        1441.0            LONGFELLOW                 NaN   
4                        2449.0             CHURCHILL                 NaN   
...                         ...                   ...                 ...   
250301                  10701.0           SANTA MARIA                 NaN   
250302                  10701.0             MEYERS RD                 NaN   
250303                  10701.0             MEYERS RD                 NaN   
250304                  10701.0             MEYERS RD                 NaN   
250305                  10701.0             MEYERS RD                 NaN   

        mailing_address_str_number mailing_address_str_name     city  ...  \
0                              3.0                S. WICKER  CHICAGO  ...   
1                           2959.0       Martin Luther King  Detroit  ...   
2                          23658.0                 P.O. BOX  DETROIT  ...   
3                              5.0                ST. CLAIR  DETROIT  ...   
4                           7449.0                CHURCHILL  DETROIT  ...   
...                            ...                      ...      ...  ...   
250301                      1715.0                   MEYERS  DETROIT  ...   
250302                      1715.0                   MEYERS  DETROIT  ...   
250303                      1715.0                   MEYERS  DETROIT  ...   
250304                      1715.0                   MEYERS  DETROIT  ...   
250305                      1715.0                   MEYERS  DETROIT  ...   

       clean_up_cost judgment_amount payment_amount balance_due  \
0                0.0           305.0            0.0       305.0   
1                0.0           855.0          780.0        75.0   
2                0.0             0.0            0.0         0.0   
3                0.0             0.0            0.0         0.0   
4                0.0             0.0            0.0         0.0   
...              ...             ...            ...         ...   
250301           0.0             0.0            0.0         0.0   
250302           0.0             0.0

In [44]:
q= vis_data['balance_due'] # все значения, и положительные и отрицательные.

In [45]:
q.mean()-q.median() #разница средних (и положительные и отрицательные) и медиан (и положительные и отрицательные)  

197.44905795306553

In [46]:
ssqqrrtt=np.sqrt(vis_data.balance_due[vis_data.balance_due > 0])

In [47]:
ssqqrrtt.mean()-ssqqrrtt.median() # разница "среднее из корней (только положительных)" - "медиана из корней (только положител)"

-0.4525960609393067

In [48]:
q_plus=vis_data.balance_due[vis_data.balance_due > 0] #толтко положительные значения 

In [49]:
np.mean(q_plus)-np.median(q_plus) #разница "среднее только положительных значений"-"медиана только положительных значений"

100.43317450863628

In [50]:
latlons

NameError: name 'latlons' is not defined

In [51]:
df_xls_sheet1 = pd.read_excel('latlons.xls', sheetname='latlons', header=None)

TypeError: read_excel() got an unexpected keyword argument `sheetname`

In [52]:
file = 'latlons.xls'


In [53]:
file

'latlons.xls'